"""Add HospitalMatching and DecisionLog tables

Revision ID: b33d89d03ce7
Revises: f5b5e8e6c686
Create Date: 2026-09-16 18:44:43.431808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33d89d03ce7'
down_revision: Union[str, Sequence[str], None] = 'f5b5e8e6c686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_decision_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=64), nullable=False),
    sa.Column('decision_type', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('reason_description', sa.Text(), nullable=True),
    sa.Column('actor_name', sa.String(length=128), nullable=False),
    sa.Column('actor_role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['emergency_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_decision_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_decision_logs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_decision_logs_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('hospital_match_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_hospital_id', sa.String(length=64), nullable=True),
    sa.Column('confirmed_destination_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('candidates_payload', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['emergency_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_destination_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommended_hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_match_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_match_records_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_match_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_match_records_case_id'))

    op.drop_table('hospital_match_records')
    with op.batch_alter_table('hospital_decision_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_decision_logs_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_decision_logs_case_id'))

    op.drop_table('hospital_decision_logs')
    # ### end Alembic commands ###
