"""Add AIStructuredReport table

Revision ID: f5b5e8e6c686
Revises: 1c0dca3eea9a
Create Date: 2026-09-16 17:57:53.465588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b5e8e6c686'
down_revision: Union[str, Sequence[str], None] = '1c0dca3eea9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_structured_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_report_id', sa.String(length=36), nullable=False),
    sa.Column('incident_summary', sa.Text(), nullable=False),
    sa.Column('incident_category', sa.String(length=128), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('consciousness', sa.String(length=64), nullable=False),
    sa.Column('breathing', sa.String(length=64), nullable=False),
    sa.Column('visible_concerns', sa.JSON(), nullable=False),
    sa.Column('location_summary', sa.String(length=255), nullable=False),
    sa.Column('extracted_keywords', sa.JSON(), nullable=False),
    sa.Column('uncertainty_flags', sa.JSON(), nullable=False),
    sa.Column('missing_information', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('structured_payload', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['emergency_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citizen_report_id'], ['citizen_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_structured_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_structured_reports_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_structured_reports_citizen_report_id'), ['citizen_report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_structured_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_structured_reports_citizen_report_id'))
        batch_op.drop_index(batch_op.f('ix_ai_structured_reports_case_id'))

    op.drop_table('ai_structured_reports')
    # ### end Alembic commands ###
