import { EMSUnit, EMSCase } from '@/types/ems';

export const DEFAULT_EMS_UNIT: EMSUnit = {
  unitId: 'ALS-04',
  unitType: 'ALS (Advanced Life Support)',
  callSign: 'Alpha-4-Medic',
  status: 'Transporting',
  crew: {
    leadParamedic: 'Paramedic Mark Vance (EMT-P)',
    driverParamedic: 'EMT-Intermediate Liam Brooks',
    medicalDirector: 'Dr. Robert Chen, MD (EMS Medical Direction)',
    contactNumber: '+1 (555) 019-7744',
  },
  currentSpeedKmH: 54,
  fuelOrBatteryPercent: 88,
  currentLocationName: 'Simulated: Sector 48 Corridor (Heading North on Expressway)',
};

export const INITIAL_EMS_CASES: Record<string, EMSCase> = {
  'LS-2026-001': {
    id: 'LS-2026-001',
    incidentType: 'Acute STEMI / Severe Chest Pain',
    operationalPriority: 'Critical',
    patientAge: 58,
    patientSex: 'Male',
    patientCount: 1,
    assignedUnitId: 'ALS-04',
    distanceRemainingKm: 6.2,
    etaMinutes: 11,
    timeAssigned: '14:28 UTC (12 mins ago)',
    lastUpdated: '14:38 UTC (2 mins ago)',
    transportStatus: 'Transporting',
    patientStatus: 'Requires close monitoring',
    citizenReport: {
      incidentType: 'Chest Pain / Heart Problem',
      reportedObservations: 'Middle-aged male collapsed in office lobby holding chest, diaphoretic and pale.',
      reportedConsciousness: 'Awake but slurred speech and clutching left arm',
      reportedBreathing: 'Rapid and shallow breathing',
      reportedConcerns: ['Severe Chest Pain', 'Difficulty Breathing', 'Cold Sweats'],
      reportedPeopleCount: 1,
      reportedLocation: 'Cyber Hub Building 8, Sector 24, Gurugram',
      landmark: 'Near Tower B Reception Gate',
      additionalNotes: 'Colleague administered 1 baby aspirin prior to EMS arrival.',
      reportedAt: '14:26 UTC',
    },
    emsVerification: {
      consciousness: 'Responding',
      breathing: 'Abnormal',
      bleeding: 'Not present',
      airway: 'Patent',
      lastVerifiedAt: '14:34 UTC',
      verifiedBy: 'Paramedic Mark Vance',
      clinicalNotes: '12-lead ECG confirmed 3mm ST-elevation in leads V2-V5 (Anterior STEMI). Sublingual nitroglycerin & 300mg clopidogrel administered en-route.',
    },
    vitals: {
      heartRate: 104,
      systolicBp: 128,
      diastolicBp: 82,
      oxygenSaturation: 96,
      respiratoryRate: 20,
      temperature: 36.8,
      gcs: 15,
      painScore: 8,
      bloodGlucose: 124,
      recordedAt: '14:38 UTC',
      recordedBy: 'Paramedic Mark Vance',
      isVerified: true,
    },
    destinationHospital: {
      hospitalId: 'HOSP-CITYCARE-01',
      name: 'CityCare Emergency Hospital',
      traumaLevel: 'Level-1 Comprehensive Trauma & STEMI Center',
      distanceKm: 6.2,
      etaMinutes: 11,
      acknowledgementState: 'Acknowledged',
      assignedBay: 'Resuscitation Bay 1 (Code Red)',
      traumaTeamStatus: 'Standby',
      cathLabStatus: 'Ready',
      coordinatorName: 'Dr. Sarah Jenkins',
      coordinatorContact: '+1 (555) 019-4820',
    },
    timeline: [
      {
        id: 't-001-1',
        timestamp: '14:26:10 UTC',
        relativeTime: '14 mins ago',
        title: 'Emergency Call Received',
        description: 'Citizen reported acute chest pain in office tower.',
        actor: 'Citizen',
        stage: 'Assigned',
      },
      {
        id: 't-001-2',
        timestamp: '14:28:00 UTC',
        relativeTime: '12 mins ago',
        title: 'EMS Unit ALS-04 Dispatched',
        description: 'Advanced Life Support crew assigned to incident.',
        actor: 'System',
        stage: 'Responding to Scene',
      },
      {
        id: 't-001-3',
        timestamp: '14:32:15 UTC',
        relativeTime: '8 mins ago',
        title: 'Arrived On Scene',
        description: 'Unit ALS-04 established contact with patient.',
        actor: 'EMS',
        stage: 'On Scene',
      },
      {
        id: 't-001-4',
        timestamp: '14:34:40 UTC',
        relativeTime: '6 mins ago',
        title: 'Primary Assessment & 12-Lead ECG',
        description: 'Verified ST-elevation; oxygen 2L/min nasal cannula started.',
        actor: 'EMS',
        stage: 'Patient Loaded',
      },
      {
        id: 't-001-5',
        timestamp: '14:36:20 UTC',
        relativeTime: '4 mins ago',
        title: 'Hospital Pre-Alert Acknowledged',
        description: 'CityCare ED acknowledged pre-arrival handoff; Cath Lab activated.',
        actor: 'Hospital',
        stage: 'Transporting',
      },
      {
        id: 't-001-6',
        timestamp: '14:38:00 UTC',
        relativeTime: '2 mins ago',
        title: 'En-Route Telemetry Synchronized',
        description: 'Updated HR 104 bpm, SpO2 96%, BP 128/82 transmitted to hospital console.',
        actor: 'EMS',
        stage: 'Transporting',
      },
    ],
  },
  'LS-2026-002': {
    id: 'LS-2026-002',
    incidentType: 'Severe Multi-Vehicle Collision',
    operationalPriority: 'Critical',
    patientAge: 29,
    patientSex: 'Female',
    patientCount: 2,
    assignedUnitId: 'ALS-04',
    distanceRemainingKm: 14.8,
    etaMinutes: 22,
    timeAssigned: '14:35 UTC (5 mins ago)',
    lastUpdated: '14:39 UTC (1 min ago)',
    transportStatus: 'On Scene',
    patientStatus: 'Deteriorating',
    citizenReport: {
      incidentType: 'Road Traffic Accident / Entrapment',
      reportedObservations: 'High-speed two-car head-on collision. Driver pinned behind steering column with visible severe head & leg injuries.',
      reportedConsciousness: 'Unconscious / non-responsive to voice',
      reportedBreathing: 'Agonal / shallow gasping',
      reportedConcerns: ['Severe Head Injury', 'Heavy Bleeding', 'Entrapment', 'Unresponsive'],
      reportedPeopleCount: 2,
      reportedLocation: 'NH-48 Flyover, Near Signature Tower Exit',
      landmark: 'Northbound lane under billboard',
      additionalNotes: 'Vehicle fluids leaking, fire engine on scene for extrication.',
      reportedAt: '14:33 UTC',
    },
    emsVerification: {
      consciousness: 'Not responding',
      breathing: 'Abnormal',
      bleeding: 'Present',
      airway: 'Compromised',
      lastVerifiedAt: '14:39 UTC',
      verifiedBy: 'Paramedic Mark Vance',
      clinicalNotes: 'Extricated by rescue squad. Severe blunt thoracic trauma and open right femur fracture. Suctioned airway, OPA inserted. Tourniquet applied to right lower limb.',
    },
    vitals: {
      heartRate: 138,
      systolicBp: 86,
      diastolicBp: 52,
      oxygenSaturation: 89,
      respiratoryRate: 28,
      temperature: 35.9,
      gcs: 7,
      painScore: 10,
      recordedAt: '14:39 UTC',
      recordedBy: 'Paramedic Mark Vance',
      isVerified: true,
    },
    destinationHospital: {
      hospitalId: 'HOSP-CITYCARE-01',
      name: 'CityCare Emergency Hospital',
      traumaLevel: 'Level-1 Comprehensive Trauma Center',
      distanceKm: 14.8,
      etaMinutes: 22,
      acknowledgementState: 'Acknowledged',
      assignedBay: 'Resuscitation Bay 2 (Trauma / Surgical)',
      traumaTeamStatus: 'Ready',
      coordinatorName: 'Dr. Sarah Jenkins',
      coordinatorContact: '+1 (555) 019-4820',
    },
    timeline: [
      {
        id: 't-002-1',
        timestamp: '14:33:10 UTC',
        relativeTime: '7 mins ago',
        title: 'Multi-Vehicle Collision Reported',
        description: 'Bystander reported high-speed impact with trapped driver.',
        actor: 'Citizen',
        stage: 'Assigned',
      },
      {
        id: 't-002-2',
        timestamp: '14:35:00 UTC',
        relativeTime: '5 mins ago',
        title: 'ALS Unit Assigned',
        description: 'ALS-04 routed to highway coordinates.',
        actor: 'System',
        stage: 'Responding to Scene',
      },
      {
        id: 't-002-3',
        timestamp: '14:38:45 UTC',
        relativeTime: '1 min ago',
        title: 'Arrived On Highway Scene',
        description: 'Commenced immediate rapid trauma assessment and airway stabilization.',
        actor: 'EMS',
        stage: 'On Scene',
      },
    ],
  },
  'LS-2026-003': {
    id: 'LS-2026-003',
    incidentType: 'Acute Ischemic Stroke (LVO Suspected)',
    operationalPriority: 'High',
    patientAge: 72,
    patientSex: 'Female',
    patientCount: 1,
    assignedUnitId: 'ALS-04',
    distanceRemainingKm: 0.4,
    etaMinutes: 1,
    timeAssigned: '14:10 UTC (30 mins ago)',
    lastUpdated: '14:37 UTC (3 mins ago)',
    transportStatus: 'Arrived at Hospital',
    patientStatus: 'Stable',
    citizenReport: {
      incidentType: 'Stroke / Sudden Weakness',
      reportedObservations: 'Family member noticed right-sided facial droop and right arm flaccidity during breakfast. Onset 40 mins ago.',
      reportedConsciousness: 'Awake, expressive aphasia',
      reportedBreathing: 'Normal',
      reportedConcerns: ['Facial Droop', 'Arm Weakness', 'Speech Slurred'],
      reportedPeopleCount: 1,
      reportedLocation: 'Sector 54, Golf Course Road, Gurugram',
      landmark: 'Tower 3, Palm Springs Residences',
      additionalNotes: 'Patient has history of atrial fibrillation and hypertension.',
      reportedAt: '14:08 UTC',
    },
    emsVerification: {
      consciousness: 'Responding',
      breathing: 'Normal',
      bleeding: 'Not present',
      airway: 'Patent',
      lastVerifiedAt: '14:22 UTC',
      verifiedBy: 'Paramedic Mark Vance',
      clinicalNotes: 'CPSS 3/3 (Face, Arm, Speech). LAMS score 4. Blood glucose 110 mg/dL. CT Angiography team pre-alerted.',
    },
    vitals: {
      heartRate: 84,
      systolicBp: 168,
      diastolicBp: 98,
      oxygenSaturation: 98,
      respiratoryRate: 16,
      temperature: 36.9,
      gcs: 14,
      painScore: 2,
      bloodGlucose: 110,
      recordedAt: '14:36 UTC',
      recordedBy: 'Paramedic Mark Vance',
      isVerified: true,
    },
    destinationHospital: {
      hospitalId: 'HOSP-CITYCARE-01',
      name: 'CityCare Emergency Hospital',
      traumaLevel: 'Comprehensive Stroke Center',
      distanceKm: 0.4,
      etaMinutes: 1,
      acknowledgementState: 'Acknowledged',
      assignedBay: 'Stroke Resuscitation Suite',
      traumaTeamStatus: 'Ready',
      coordinatorName: 'Dr. Sarah Jenkins',
      coordinatorContact: '+1 (555) 019-4820',
    },
    timeline: [
      {
        id: 't-003-1',
        timestamp: '14:08:00 UTC',
        relativeTime: '32 mins ago',
        title: 'Stroke Symptoms Reported by Family',
        description: 'Sudden weakness and speech loss observed.',
        actor: 'Citizen',
        stage: 'Assigned',
      },
      {
        id: 't-003-2',
        timestamp: '14:10:00 UTC',
        relativeTime: '30 mins ago',
        title: 'Dispatched & Responded',
        description: 'Unit ALS-04 en-route.',
        actor: 'System',
        stage: 'Responding to Scene',
      },
      {
        id: 't-003-3',
        timestamp: '14:18:00 UTC',
        relativeTime: '22 mins ago',
        title: 'On-Scene Assessment',
        description: 'Stroke score verified; IV access established.',
        actor: 'EMS',
        stage: 'On Scene',
      },
      {
        id: 't-003-4',
        timestamp: '14:24:00 UTC',
        relativeTime: '16 mins ago',
        title: 'En-Route to Comprehensive Stroke ED',
        description: 'Direct transit initiated; pre-alert dispatched to CT radiology.',
        actor: 'EMS',
        stage: 'Transporting',
      },
      {
        id: 't-003-5',
        timestamp: '14:37:00 UTC',
        relativeTime: '3 mins ago',
        title: 'Ambulance Pulled Into Emergency Bay',
        description: 'Preparing for immediate bedside CT handover.',
        actor: 'EMS',
        stage: 'Arrived at Hospital',
      },
    ],
  },
  'LS-2026-101': {
    id: 'LS-2026-101',
    incidentType: 'Roadside Bystander Accident',
    operationalPriority: 'High',
    patientAge: 35,
    patientSex: 'Unknown',
    patientCount: 2,
    assignedUnitId: 'ALS-04',
    distanceRemainingKm: 4.5,
    etaMinutes: 8,
    timeAssigned: '14:38 UTC (2 mins ago)',
    lastUpdated: '14:39 UTC (Just now)',
    transportStatus: 'Assigned',
    patientStatus: 'Unable to assess',
    citizenReport: {
      incidentType: 'Road Accident',
      reportedObservations: 'Two-wheeler collision with road divider. Rider thrown off bike.',
      reportedConsciousness: 'Unresponsive at distance',
      reportedBreathing: 'Uncertain',
      reportedConcerns: ['Severe Head Injury', 'Observable Bleeding'],
      reportedPeopleCount: 2,
      reportedLocation: 'GD Goenka University Area, Sector 48, Gurugram',
      landmark: 'Near University Main Gate',
      additionalNotes: 'Bystander reported from roadside. Helmet cracked on ground.',
      reportedAt: '14:38 UTC',
    },
    emsVerification: {
      consciousness: 'Unverified',
      breathing: 'Unverified',
      bleeding: 'Unverified',
      airway: 'Unverified',
      clinicalNotes: 'Awaiting on-scene arrival for formal triage.',
    },
    vitals: {
      heartRate: 0,
      systolicBp: 0,
      diastolicBp: 0,
      oxygenSaturation: 0,
      respiratoryRate: 0,
      temperature: 0,
      gcs: 0,
      recordedAt: 'Pending on-scene assessment',
      recordedBy: 'ALS-04',
      isVerified: false,
    },
    destinationHospital: {
      hospitalId: 'HOSP-CITYCARE-01',
      name: 'CityCare Emergency Hospital',
      traumaLevel: 'Level-1 Comprehensive Trauma Center',
      distanceKm: 8.4,
      etaMinutes: 14,
      acknowledgementState: 'Pre-Alert Queued',
      traumaTeamStatus: 'Preparing',
      coordinatorName: 'Dr. Sarah Jenkins',
      coordinatorContact: '+1 (555) 019-4820',
    },
    timeline: [
      {
        id: 't-101-1',
        timestamp: '14:38:00 UTC',
        relativeTime: '2 mins ago',
        title: 'Citizen Emergency Report Transmitted',
        description: 'Bystander intake synchronized via LifeSync Citizen Portal.',
        actor: 'Citizen',
        stage: 'Assigned',
      },
      {
        id: 't-101-2',
        timestamp: '14:39:10 UTC',
        relativeTime: 'Just now',
        title: 'Assigned to ALS-04',
        description: 'Unit notified for immediate response.',
        actor: 'System',
        stage: 'Assigned',
      },
    ],
  },
};
