import { EmergencyCase, HospitalProfile, HospitalResourceItem } from '@/types/hospital';

export const INITIAL_HOSPITAL_PROFILE: HospitalProfile = {
  id: 'HOSP-CITYCARE-01',
  name: 'CityCare Emergency Hospital',
  shortName: 'CityCare ED',
  traumaLevel: 'Level-1 Comprehensive Trauma Center',
  operationalStatus: 'Operational',
  diversionActive: false,
  activeSurgeLevel: 'Normal',
  totalBays: 12,
  availableBays: 5,
  onDutyCoordinator: 'Dr. Sarah Jenkins',
  coordinatorRole: 'Emergency Medicine Attending / Triage Lead',
  phone: '+1 (555) 019-4820',
  address: '742 Metro Medical Boulevard, Sector 4',
  capabilities: [
    { name: '24/7 Cardiac Catheterization Lab', available: true, description: 'STEMI intervention pathway with immediate on-call interventionalist' },
    { name: 'Comprehensive Stroke Center', available: true, description: 'Rapid CT Angiography & endovascular thrombectomy team' },
    { name: 'Level-1 Trauma Resuscitation Suites', available: true, description: '2 designated resuscitation bays with rapid infusers & ultrasound' },
    { name: '24/7 Emergency Blood Bank', available: true, description: 'Uncrossmatched O-Negative & O-Positive emergency units on standby' },
    { name: 'Emergency Surgical Theatres', available: true, description: 'Dedicated trauma OR available within 15 minutes' },
    { name: 'Pediatric Emergency Stabilization', available: true, description: 'Specialized pediatric resuscitation equipment & PICU bridge' },
  ],
};

export const INITIAL_HOSPITAL_RESOURCES: HospitalResourceItem[] = [
  {
    id: 'RES-BAY-01',
    name: 'Resuscitation Bay 1 (Code Red / Cardiac)',
    category: 'Resuscitation Unit',
    status: 'Ready',
    totalCapacity: 1,
    availableCapacity: 1,
    location: 'ED Red Zone - Bay 1',
    lastUpdated: '2 mins ago',
    notes: 'Defibrillator & telemetry monitor calibrated. Lucas device on standby.',
  },
  {
    id: 'RES-BAY-02',
    name: 'Resuscitation Bay 2 (Trauma / Surgical)',
    category: 'Resuscitation Unit',
    status: 'Occupied',
    totalCapacity: 1,
    availableCapacity: 0,
    assignedCaseId: 'LS-2026-002',
    location: 'ED Red Zone - Bay 2',
    lastUpdated: '8 mins ago',
    notes: 'Reserved for incoming poly-trauma (LS-2026-002). Rapid infuser primed.',
  },
  {
    id: 'RES-TRAUMA-01',
    name: 'Trauma Bay 1',
    category: 'Emergency Bay',
    status: 'Ready',
    totalCapacity: 1,
    availableCapacity: 1,
    location: 'ED Trauma Wing',
    lastUpdated: '12 mins ago',
    notes: 'Full thoracotomy tray and ultrasound probe verified.',
  },
  {
    id: 'RES-TRAUMA-02',
    name: 'Trauma Bay 2',
    category: 'Emergency Bay',
    status: 'Ready',
    totalCapacity: 1,
    availableCapacity: 1,
    location: 'ED Trauma Wing',
    lastUpdated: '15 mins ago',
    notes: 'Standard adult trauma setup available.',
  },
  {
    id: 'RES-CATH-01',
    name: 'Cardiac Cath Lab 1',
    category: 'Specialist Team',
    status: 'Ready',
    totalCapacity: 1,
    availableCapacity: 1,
    location: 'Cardiology 2nd Floor (Direct Lift Access)',
    lastUpdated: '5 mins ago',
    notes: 'Interventionalist Dr. Rao on standby for acute STEMI alerts.',
  },
  {
    id: 'RES-CT-01',
    name: 'Emergency CT Scanner 1 (Angio-capable)',
    category: 'Diagnostics / Imaging',
    status: 'Ready',
    totalCapacity: 1,
    availableCapacity: 1,
    location: 'ED Diagnostic Radiology Suite',
    lastUpdated: '10 mins ago',
    notes: 'Cleared for stroke & acute polytrauma protocols.',
  },
  {
    id: 'RES-BLOOD-01',
    name: 'Emergency Blood Bank Supply',
    category: 'Blood Bank',
    status: 'Ready',
    totalCapacity: 8,
    availableCapacity: 6,
    location: 'Central Blood Bank / ED Satellite Fridge',
    lastUpdated: '1 hour ago',
    notes: '6 Units O-Negative and 8 Units O-Positive ready for immediate release.',
  },
  {
    id: 'RES-OR-03',
    name: 'Emergency Trauma OR 3',
    category: 'Surgical / OR',
    status: 'Limited',
    totalCapacity: 1,
    availableCapacity: 1,
    location: 'Surgical Floor 3',
    lastUpdated: '25 mins ago',
    notes: 'Anesthesia team on standby; nursing changeover in progress.',
  },
];

export const INITIAL_EMERGENCY_CASES: EmergencyCase[] = [
  {
    id: 'LS-2026-001',
    incidentType: 'Acute Coronary Syndrome / Suspected STEMI',
    operationalPriority: 'Critical',
    status: 'Alerted',
    patientAge: 58,
    patientSex: 'Male',
    patientCount: 1,
    reportedLocation: 'Corner of 4th Ave & Oak St (Office Complex)',
    destinationHospitalId: 'HOSP-CITYCARE-01',
    destinationHospitalName: 'CityCare Emergency Hospital',
    timeReported: '14:02 UTC',
    timeAlerted: '14:04 UTC',
    clinicalSummary: {
      chiefComplaint: 'Crushing retrosternal chest pain radiating to left jaw and shoulder',
      reportedSymptoms: [
        'Severe chest pressure (10/10)',
        'Profuse diaphoresis (cold sweats)',
        'Shortness of breath (dyspnea)',
        'Nausea and lightheadedness',
      ],
      pertinentNegatives: [
        'No prior documented STEMI (unconfirmed)',
        'No recent trauma',
        'No gastrointestinal bleeding reported',
      ],
      mechanismOfInjury: 'Non-traumatic sudden onset during sedentary desk work',
      symptomOnsetMinutes: 35,
      consciousness: 'Alert',
      knownAllergies: ['Penicillin (Moderate rash)'],
      knownMedications: ['Atorvastatin 20mg', 'Amlodipine 5mg'],
      relevantHistory: ['Hypertension (5 years)', 'Hyperlipidemia', 'Smoker (15 pack-years)'],
      initialObservations: 'Caller notes patient appeared pale, clutching chest, unable to walk without assistance.',
      aiStructuringNotes: 'High-risk cardiovascular indicators detected. Deterministic Safety Rule [CARD-01] triggered. Pre-arrival Cath Lab staging advised.',
      specialtyRequirements: ['24/7 Cath Lab', 'Resuscitation Bay', 'Cardiology Consult'],
    },
    emsUnit: {
      unitId: 'ALS-04',
      vehicleType: 'ALS (Advanced Life Support)',
      crewNames: ['Paramedic R. Davis', 'EMT-P M. Torres'],
      crewContact: '+1 (555) 012-7844',
      currentLocationName: 'Grand Central Expressway (Southbound)',
      speedKmH: 62,
      distanceRemainingKm: 3.4,
      etaMinutes: 6,
      transportStatus: 'Transporting',
      lastTelemetryTimestamp: '14:07 UTC',
      verifiedVitals: {
        heartRate: 112,
        systolicBp: 92,
        diastolicBp: 60,
        respiratoryRate: 22,
        oxygenSaturation: 92,
        gcs: 15,
        temperature: 36.8,
        painScale: 9,
        lastUpdated: '14:06 UTC',
        source: 'EMS Verified',
      },
    },
    timeline: [
      {
        id: 'evt-101',
        timestamp: '14:02:10 UTC',
        relativeTime: '6 mins ago',
        title: 'Emergency Reported by Bystander',
        description: 'Bystander initiated voice intake reporting collapsed male with crushing chest pain.',
        actor: 'Citizen App (Caller: J. Miller)',
        actorRole: 'Bystander',
        stage: 'Alerted',
        type: 'bystander',
      },
      {
        id: 'evt-102',
        timestamp: '14:02:45 UTC',
        relativeTime: '5.5 mins ago',
        title: 'Pre-Arrival Information Structured',
        description: 'NLP extracted clinical indicators: 58M, chest pain, diaphoresis. Safety Rule CARD-01 escalated priority to Critical.',
        actor: 'LifeSync Coordination Core',
        actorRole: 'System Engine',
        stage: 'Alerted',
        type: 'system',
      },
      {
        id: 'evt-103',
        timestamp: '14:03:10 UTC',
        relativeTime: '5 mins ago',
        title: 'ALS Ambulance Unit Dispatched',
        description: 'ALS Unit 04 dispatched. Target hospital matched: CityCare Emergency Hospital (Cath Lab Active).',
        actor: 'Regional Dispatch Engine',
        actorRole: 'System Engine',
        stage: 'Alerted',
        type: 'ems',
      },
      {
        id: 'evt-104',
        timestamp: '14:04:00 UTC',
        relativeTime: '4 mins ago',
        title: 'Pre-Arrival Alert Broadcast to Hospital',
        description: 'Pre-arrival notification sent to CityCare ED Operations Desk. Awaiting acknowledgement.',
        actor: 'LifeSync Alert Router',
        actorRole: 'System Engine',
        stage: 'Alerted',
        type: 'hospital',
      },
      {
        id: 'evt-105',
        timestamp: '14:06:20 UTC',
        relativeTime: '2 mins ago',
        title: 'EMS En-Route Telemetry & Vitals Sync',
        description: 'Paramedic verified on-scene 12-lead telemetry: ST-elevation in II, III, aVF. BP 92/60, SpO2 92% on room air.',
        actor: 'Paramedic R. Davis',
        actorRole: 'ALS-04 Crew',
        stage: 'Alerted',
        type: 'ems',
      },
    ],
    readinessChecklist: [
      { id: 'chk-1', label: 'Resuscitation Bay 1 Prepared & Monitored', completed: false, requiredFor: 'Resuscitation' },
      { id: 'chk-2', label: 'Cath Lab On-Call Interventionalist Paged', completed: false, requiredFor: 'Cardiology' },
      { id: 'chk-3', label: 'Defibrillator & Transcutaneous Pacing Ready', completed: false, requiredFor: 'Resuscitation' },
      { id: 'chk-4', label: 'Heparin & Dual Antiplatelet Protocol Staged', completed: false, requiredFor: 'Pharmacy' },
    ],
  },
  {
    id: 'LS-2026-002',
    incidentType: 'High-Velocity Road Traffic Incident / Poly-Trauma',
    operationalPriority: 'Critical',
    status: 'Acknowledged',
    patientAge: 24,
    patientSex: 'Female',
    patientCount: 1,
    reportedLocation: 'Interstate 80 Mile Marker 14 (Eastbound)',
    destinationHospitalId: 'HOSP-CITYCARE-01',
    destinationHospitalName: 'CityCare Emergency Hospital',
    assignedBay: 'Resuscitation Bay 2',
    timeReported: '13:58 UTC',
    timeAlerted: '14:00 UTC',
    timeAcknowledged: '14:01 UTC',
    acknowledgedBy: 'Dr. Sarah Jenkins (ED Lead)',
    clinicalSummary: {
      chiefComplaint: 'Multiple blunt force trauma, seatbelt sign, left chest wall deformity with paradoxical movement',
      reportedSymptoms: [
        'Decreased breath sounds on left',
        'Severe pelvic tenderness',
        'Altered mental status (GCS 12: E3 V4 M5)',
        'Extensive subcutaneous emphysema',
      ],
      pertinentNegatives: [
        'No open cranial wound observed',
        'Pupils equal and reactive (3mm)',
      ],
      mechanismOfInjury: 'Roll-over motor vehicle collision at estimated 90 km/h with airbag deployment',
      symptomOnsetMinutes: 20,
      consciousness: 'Voice',
      knownAllergies: ['NKDA (No Known Drug Allergies)'],
      knownMedications: ['Oral Contraceptive'],
      relevantHistory: ['No known chronic illnesses'],
      initialObservations: 'Extricated by fire-rescue. Rigid cervical collar applied. Left pupil 3mm, Right 3mm.',
      aiStructuringNotes: 'Major trauma protocol triggered. High likelihood of pneumothorax and internal pelvic hemorrhage.',
      specialtyRequirements: ['Level-1 Trauma Team', 'Blood Bank (Massive Transfusion)', 'CT Angiography', 'Trauma OR'],
    },
    emsUnit: {
      unitId: 'ALS-02',
      vehicleType: 'ALS (Advanced Life Support)',
      crewNames: ['Paramedic K. Patel', 'Paramedic J. Gomez'],
      crewContact: '+1 (555) 012-9901',
      currentLocationName: 'Highway 101 Access Ramp',
      speedKmH: 74,
      distanceRemainingKm: 6.8,
      etaMinutes: 11,
      transportStatus: 'Transporting',
      lastTelemetryTimestamp: '14:07 UTC',
      verifiedVitals: {
        heartRate: 128,
        systolicBp: 86,
        diastolicBp: 52,
        respiratoryRate: 28,
        oxygenSaturation: 89,
        gcs: 12,
        temperature: 36.4,
        painScale: 8,
        lastUpdated: '14:05 UTC',
        source: 'EMS Verified',
      },
    },
    timeline: [
      {
        id: 'evt-201',
        timestamp: '13:58:00 UTC',
        relativeTime: '10 mins ago',
        title: 'Crash Detection & Emergency Reported',
        description: 'Automatic crash notification & 911 relay. Vehicle rollover confirmed with 1 trapped occupant.',
        actor: 'Bystander & Traffic Camera',
        actorRole: 'Intake Source',
        stage: 'Alerted',
        type: 'bystander',
      },
      {
        id: 'evt-202',
        timestamp: '14:00:15 UTC',
        relativeTime: '8 mins ago',
        title: 'Pre-Arrival Alert Broadcast to Hospital',
        description: 'Level-1 Trauma pre-arrival alert transmitted to CityCare Emergency Hospital.',
        actor: 'LifeSync Core Dispatch',
        actorRole: 'System Engine',
        stage: 'Alerted',
        type: 'system',
      },
      {
        id: 'evt-203',
        timestamp: '14:01:10 UTC',
        relativeTime: '7 mins ago',
        title: 'Hospital Acknowledged & Bay Allocated',
        description: 'Dr. Jenkins acknowledged alert and reserved Resuscitation Bay 2 for trauma staging.',
        actor: 'Dr. Sarah Jenkins',
        actorRole: 'Hospital ED Lead',
        stage: 'Acknowledged',
        type: 'hospital',
      },
      {
        id: 'evt-204',
        timestamp: '14:05:30 UTC',
        relativeTime: '3 mins ago',
        title: 'EMS En-Route Needle Decompression Performed',
        description: 'Paramedics performed left anterior needle decompression en route. SpO2 improved from 82% to 89%.',
        actor: 'Paramedic K. Patel',
        actorRole: 'ALS-02 Crew',
        stage: 'En Route',
        type: 'ems',
      },
    ],
    readinessChecklist: [
      { id: 'chk-201', label: 'Resuscitation Bay 2 Staged for Trauma', completed: true, requiredFor: 'Resuscitation' },
      { id: 'chk-202', label: 'Blood Bank: 4 Units O-Neg on Standby in ED Fridge', completed: true, requiredFor: 'Blood Bank' },
      { id: 'chk-203', label: 'Trauma Surgery Team Paged & En Route to Bay', completed: true, requiredFor: 'Surgical' },
      { id: 'chk-204', label: 'Rapid Infuser / Belmont Warmer Primed', completed: true, requiredFor: 'Nursing' },
      { id: 'chk-205', label: 'CT Scanner 1 Cleared for Immediate Pan-Scan', completed: false, requiredFor: 'Radiology' },
    ],
  },
  {
    id: 'LS-2026-003',
    incidentType: 'Acute Neurological Deficit / Suspected Stroke',
    operationalPriority: 'High',
    status: 'Alerted',
    patientAge: 67,
    patientSex: 'Male',
    patientCount: 1,
    reportedLocation: '412 West Valley Residential Community',
    destinationHospitalId: 'HOSP-CITYCARE-01',
    destinationHospitalName: 'CityCare Emergency Hospital',
    timeReported: '14:01 UTC',
    timeAlerted: '14:03 UTC',
    clinicalSummary: {
      chiefComplaint: 'Right-sided facial droop, slurred expressive dysphasia, and right arm flaccid weakness',
      reportedSymptoms: [
        'Positive Cincinnati Prehospital Stroke Scale (3/3)',
        'Arm drift (Right 0/5 motor strength)',
        'Speech slurred and garbled',
        'Mild left-sided headache',
      ],
      pertinentNegatives: [
        'No seizure activity reported',
        'No head trauma',
        'Blood glucose measured: 114 mg/dL (Normal - Rule out hypoglycemia)',
      ],
      mechanismOfInjury: 'Sudden onset while eating lunch with spouse',
      symptomOnsetMinutes: 42,
      consciousness: 'Alert',
      knownAllergies: ['Sulfa drugs'],
      knownMedications: ['Metformed 500mg', 'Lisinopril 10mg'],
      relevantHistory: ['Type 2 Diabetes Mellitus', 'Prior TIA 2 years ago', 'Hypertension'],
      initialObservations: 'Last Seen Normal: 13:20 UTC (Symptom onset well within standard 4.5h thrombolytic window).',
      aiStructuringNotes: 'Time-critical Code Stroke candidate. Last known well < 45m. Immediate non-contrast CT & CT Angio indicated.',
      specialtyRequirements: ['Comprehensive Stroke Team', 'Emergency CT Angiography', 'Neurology Consult'],
    },
    emsUnit: {
      unitId: 'BLS-09',
      vehicleType: 'BLS (Basic Life Support)',
      crewNames: ['EMT T. Bradley', 'EMT S. Vance'],
      crewContact: '+1 (555) 012-3344',
      currentLocationName: 'Parkway Blvd & 12th St',
      speedKmH: 50,
      distanceRemainingKm: 8.2,
      etaMinutes: 14,
      transportStatus: 'Transporting',
      lastTelemetryTimestamp: '14:07 UTC',
      verifiedVitals: {
        heartRate: 88,
        systolicBp: 168,
        diastolicBp: 98,
        respiratoryRate: 18,
        oxygenSaturation: 97,
        gcs: 14,
        temperature: 37.1,
        lastUpdated: '14:05 UTC',
        source: 'EMS Verified',
      },
    },
    timeline: [
      {
        id: 'evt-301',
        timestamp: '14:01:00 UTC',
        relativeTime: '7 mins ago',
        title: 'Emergency Reported via Citizen Voice',
        description: 'Spouse reported sudden speech slurring and facial asymmetry.',
        actor: 'Citizen Intake (Caller: M. Adams)',
        actorRole: 'Bystander',
        stage: 'Alerted',
        type: 'bystander',
      },
      {
        id: 'evt-302',
        timestamp: '14:03:00 UTC',
        relativeTime: '5 mins ago',
        title: 'Code Stroke Pre-Alert Sent to Hospital',
        description: 'Pre-arrival notification sent to Stroke Receiving Coordinator at CityCare.',
        actor: 'LifeSync Core Engine',
        actorRole: 'System Engine',
        stage: 'Alerted',
        type: 'hospital',
      },
    ],
    readinessChecklist: [
      { id: 'chk-301', label: 'CT Scanner 1 Reserved on Direct-to-CT Pathway', completed: false, requiredFor: 'Radiology' },
      { id: 'chk-302', label: 'Neurology Stroke Fellow Alerted', completed: false, requiredFor: 'Neurology' },
      { id: 'chk-303', label: 'Thrombolytic / TNK Kit Verified in Pharmacy Pyxis', completed: false, requiredFor: 'Pharmacy' },
    ],
  },
  {
    id: 'LS-2026-004',
    incidentType: 'Pediatric Acute Respiratory Distress / Severe Asthma',
    operationalPriority: 'High',
    status: 'Acknowledged',
    patientAge: 8,
    patientSex: 'Female',
    patientCount: 1,
    reportedLocation: 'Lincoln Elementary School, Room 204',
    destinationHospitalId: 'HOSP-CITYCARE-01',
    destinationHospitalName: 'CityCare Emergency Hospital',
    assignedBay: 'Trauma Bay 1 (Pediatric Ready)',
    timeReported: '13:52 UTC',
    timeAlerted: '13:55 UTC',
    timeAcknowledged: '13:57 UTC',
    acknowledgedBy: 'Dr. Sarah Jenkins',
    clinicalSummary: {
      chiefComplaint: 'Severe expiratory wheezing, intercostal retractions, and inability to speak in full sentences',
      reportedSymptoms: [
        'Tripod positioning',
        'Marked subcostal & suprasternal retractions',
        'Tachypnea (RR 38/min)',
        'Prolonged expiratory phase',
      ],
      pertinentNegatives: [
        'No foreign body aspiration reported',
        'No urticaria or swelling of lips/tongue',
        'No fever',
      ],
      mechanismOfInjury: 'Triggered during physical education outdoors in high pollen conditions',
      symptomOnsetMinutes: 30,
      consciousness: 'Alert',
      knownAllergies: ['Tree nuts', 'Pollen'],
      knownMedications: ['Albuterol MDI as needed'],
      relevantHistory: ['Moderate persistent asthma with 1 prior PICU admission'],
      initialObservations: 'School nurse administered 2 puffs albuterol with minimal relief. Paramedics initiated continuous nebulizer.',
      aiStructuringNotes: 'Pediatric Status Asthmaticus risk. Continuous Duoneb and IV magnesium sulfate preparation recommended.',
      specialtyRequirements: ['Pediatric Resuscitation Bay', 'Respiratory Therapy', 'PICU Backup'],
    },
    emsUnit: {
      unitId: 'ALS-06',
      vehicleType: 'ALS (Advanced Life Support)',
      crewNames: ['Paramedic L. Young', 'EMT D. Chang'],
      crewContact: '+1 (555) 012-6612',
      currentLocationName: 'Beacon St & 22nd Ave',
      speedKmH: 48,
      distanceRemainingKm: 9.6,
      etaMinutes: 18,
      transportStatus: 'Transporting',
      lastTelemetryTimestamp: '14:07 UTC',
      verifiedVitals: {
        heartRate: 142,
        systolicBp: 104,
        diastolicBp: 68,
        respiratoryRate: 36,
        oxygenSaturation: 91,
        gcs: 15,
        temperature: 36.9,
        lastUpdated: '14:04 UTC',
        source: 'EMS Verified',
      },
    },
    timeline: [
      {
        id: 'evt-401',
        timestamp: '13:52:00 UTC',
        relativeTime: '16 mins ago',
        title: 'Emergency Reported by School Nurse',
        description: 'School nurse initiated emergency call for 8-year-old in severe respiratory distress.',
        actor: 'Citizen Intake (Nurse E. Watson)',
        actorRole: 'Bystander / Nurse',
        stage: 'Alerted',
        type: 'bystander',
      },
      {
        id: 'evt-402',
        timestamp: '13:57:00 UTC',
        relativeTime: '11 mins ago',
        title: 'Hospital Acknowledged & Bay Prepared',
        description: 'ED Coordinator acknowledged case and assigned Trauma Bay 1 with pediatric airway cart.',
        actor: 'Dr. Sarah Jenkins',
        actorRole: 'Hospital ED Lead',
        stage: 'Acknowledged',
        type: 'hospital',
      },
    ],
    readinessChecklist: [
      { id: 'chk-401', label: 'Pediatric Broselow Tape & Airway Cart Staged', completed: true, requiredFor: 'Nursing' },
      { id: 'chk-402', label: 'Respiratory Therapist Paged to ED Bay 1', completed: true, requiredFor: 'Respiratory' },
      { id: 'chk-403', label: 'Continuous In-Line Albuterol/Ipratropium Ready', completed: true, requiredFor: 'Pharmacy' },
    ],
  },
  {
    id: 'LS-2026-005',
    incidentType: 'Closed Lower Extremity Deformity post Fall',
    operationalPriority: 'Moderate',
    status: 'Acknowledged',
    patientAge: 34,
    patientSex: 'Male',
    patientCount: 1,
    reportedLocation: 'Metropolitan Construction Site 3B',
    destinationHospitalId: 'HOSP-CITYCARE-01',
    destinationHospitalName: 'CityCare Emergency Hospital',
    timeReported: '13:40 UTC',
    timeAlerted: '13:44 UTC',
    timeAcknowledged: '13:48 UTC',
    clinicalSummary: {
      chiefComplaint: 'Severe pain, deformity, and edema to right lower leg after 6-foot scaffolding fall',
      reportedSymptoms: [
        'Marked right distal tib-fib angulation',
        'Intact distal pulses (dorsalis pedis palpable)',
        'Capillary refill < 2 seconds in all toes',
      ],
      pertinentNegatives: [
        'No open bone fragments / skin intact',
        'No loss of consciousness',
        'No neck or back pain',
      ],
      mechanismOfInjury: 'Fell from scaffolding (approx. 2 meters) landing awkwardly on right foot',
      symptomOnsetMinutes: 45,
      consciousness: 'Alert',
      knownAllergies: ['NKDA'],
      knownMedications: ['None'],
      relevantHistory: ['No medical history'],
      initialObservations: 'Splinted with vacuum immobilization on scene. Distal sensation intact.',
      aiStructuringNotes: 'Stable extremity trauma. Plain radiography and orthopedic reduction tray indicated.',
      specialtyRequirements: ['General ED Bay', 'X-Ray Imaging', 'Orthopedic Splinting'],
    },
    emsUnit: {
      unitId: 'BLS-14',
      vehicleType: 'BLS (Basic Life Support)',
      crewNames: ['EMT M. Hernandez', 'EMT P. Scott'],
      crewContact: '+1 (555) 012-7711',
      currentLocationName: 'Riverside Drive',
      speedKmH: 42,
      distanceRemainingKm: 14.2,
      etaMinutes: 26,
      transportStatus: 'Transporting',
      lastTelemetryTimestamp: '14:07 UTC',
      verifiedVitals: {
        heartRate: 84,
        systolicBp: 128,
        diastolicBp: 78,
        respiratoryRate: 16,
        oxygenSaturation: 99,
        gcs: 15,
        painScale: 7,
        lastUpdated: '14:02 UTC',
        source: 'EMS Verified',
      },
    },
    timeline: [
      {
        id: 'evt-501',
        timestamp: '13:40:00 UTC',
        relativeTime: '28 mins ago',
        title: 'Emergency Reported by Site Supervisor',
        description: 'Reported scaffolding fall with isolated leg injury.',
        actor: 'Citizen Intake',
        actorRole: 'Bystander',
        stage: 'Alerted',
        type: 'bystander',
      },
      {
        id: 'evt-502',
        timestamp: '13:48:00 UTC',
        relativeTime: '20 mins ago',
        title: 'Hospital Acknowledged',
        description: 'Triage coordinator accepted case for routine orthopedic ED staging.',
        actor: 'Triage Nurse D. Miller',
        actorRole: 'Hospital Staff',
        stage: 'Acknowledged',
        type: 'hospital',
      },
    ],
    readinessChecklist: [
      { id: 'chk-501', label: 'Plain Radiography Slot Queued', completed: true, requiredFor: 'Radiology' },
      { id: 'chk-502', label: 'Orthopedic Plaster & Splinting Cart Staged', completed: false, requiredFor: 'Nursing' },
    ],
  },
  {
    id: 'LS-2026-006',
    incidentType: 'Anaphylactoid Reaction post Ingestion (Stabilized)',
    operationalPriority: 'Moderate',
    status: 'Handover',
    patientAge: 45,
    patientSex: 'Female',
    patientCount: 1,
    reportedLocation: 'Central Food Plaza Bistro',
    destinationHospitalId: 'HOSP-CITYCARE-01',
    destinationHospitalName: 'CityCare Emergency Hospital',
    assignedBay: 'Trauma Bay 2',
    timeReported: '13:15 UTC',
    timeAlerted: '13:18 UTC',
    timeAcknowledged: '13:20 UTC',
    clinicalSummary: {
      chiefComplaint: 'Urticarial rash, lip swelling, and throat tightness after accidental peanut cross-contamination',
      reportedSymptoms: [
        'Diffuse erythematous hives',
        'Facial flushing and mild angioedema',
        'Breathing stabilized post-epinephrine',
      ],
      pertinentNegatives: [
        'No stridor currently',
        'No hypotension observed',
      ],
      mechanismOfInjury: 'Accidental ingestion of peanut oil salad dressing',
      symptomOnsetMinutes: 70,
      consciousness: 'Alert',
      knownAllergies: ['Peanuts (Severe)', 'Shellfish'],
      knownMedications: ['EpiPen auto-injector'],
      relevantHistory: ['Prior anaphylaxis requiring hospitalization (2021)'],
      initialObservations: 'Patient self-administered EpiPen 0.3mg IM. EMS administered supplemental IV diphenhydramine and methylprednisolone.',
      aiStructuringNotes: 'Stabilized post-epinephrine. Minimum 4-6 hour post-anaphylaxis observational monitoring required.',
      specialtyRequirements: ['ED Observation Bay', 'Airway Standby'],
    },
    emsUnit: {
      unitId: 'BLS-03',
      vehicleType: 'BLS (Basic Life Support)',
      crewNames: ['EMT B. Taylor', 'EMT H. Ross'],
      crewContact: '+1 (555) 012-9988',
      currentLocationName: 'Hospital Ambulance Bay',
      speedKmH: 0,
      distanceRemainingKm: 0,
      etaMinutes: 0,
      transportStatus: 'Handover Complete',
      lastTelemetryTimestamp: '14:07 UTC',
      verifiedVitals: {
        heartRate: 82,
        systolicBp: 118,
        diastolicBp: 74,
        respiratoryRate: 16,
        oxygenSaturation: 98,
        gcs: 15,
        painScale: 2,
        lastUpdated: '14:00 UTC',
        source: 'EMS Verified',
      },
    },
    timeline: [
      {
        id: 'evt-601',
        timestamp: '13:15:00 UTC',
        relativeTime: '52 mins ago',
        title: 'Emergency Reported',
        description: 'Bystander reported severe allergic reaction.',
        actor: 'Citizen Intake',
        actorRole: 'Bystander',
        stage: 'Alerted',
        type: 'bystander',
      },
      {
        id: 'evt-602',
        timestamp: '13:20:00 UTC',
        relativeTime: '47 mins ago',
        title: 'Hospital Acknowledged',
        description: 'Bay assigned for observation.',
        actor: 'Dr. Sarah Jenkins',
        actorRole: 'Hospital ED Lead',
        stage: 'Acknowledged',
        type: 'hospital',
      },
      {
        id: 'evt-603',
        timestamp: '14:02:00 UTC',
        relativeTime: '5 mins ago',
        title: 'Physical Arrival & Bedside Handover Complete',
        description: 'Patient received in Trauma Bay 2. Digital sign-off completed between EMT Taylor and Dr. Jenkins.',
        actor: 'Dr. Sarah Jenkins & EMT B. Taylor',
        actorRole: 'Clinical Team',
        stage: 'Handover',
        type: 'hospital',
      },
    ],
    readinessChecklist: [
      { id: 'chk-601', label: 'Observation Bay Assigned', completed: true, requiredFor: 'Nursing' },
      { id: 'chk-602', label: 'Allergy Anaphylaxis Observation Protocol Initiated', completed: true, requiredFor: 'Clinical' },
    ],
  },
];

export const DIVERT_REASON_OPTIONS = [
  { id: 'CAPACITY_EXCEEDED', label: 'Emergency Department at Maximum Surge Capacity / Zero Beds Available' },
  { id: 'SPECIALTY_OFFLINE', label: 'Required Medical Specialty Unavailable (e.g. Cath Lab / Stroke Interventionalist)' },
  { id: 'OR_COMMITTED', label: 'Trauma Surgical Theatres Fully Committed in Active Emergency Surgery' },
  { id: 'EQUIPMENT_MAINTENANCE', label: 'Critical Diagnostic Equipment Offline (e.g. CT Angiography / Ultrasound)' },
  { id: 'OTHER', label: 'Other Operational / Environmental Constraint (Requires detailed justification)' },
];
